# WORKDIR, COPY and ADD example
FROM ubuntu:latest 
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get install -y apache2 
WORKDIR /var/www/html 
COPY index.html . 
ADD https://www.docker.com/sites/default/files/d8/2019-07/Moby-logo.png ./logo.png
CMD ["ls"]
